version: '3'

services:
  postgres:
    container_name: 'sif-pg'
    image: 'postgres:14.4-alpine'
    environment:
      POSTGRES_USER: 'socious'
      POSTGRES_PASSWORD: 'passwd'
      POSTGRES_DB: 'socious'
      PGDATA: '/data/postgres'
    volumes:
      - '../sif-postgres:/data/postgres'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    restart: 'always'

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

networks:
  default:
    driver: bridge
