openapi: 3.0.0
info:
  title: Socious-API
  version: 2.2.6
servers:
  - url: http://localhost:4000
    description: Local server (for development purposes)
  - url: https://devsif.socious.io
    description: dev server (for development purposes)
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth:
    post:
      summary: create auth
      description: create auth session
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                redirect_url:
                  type: string
                  example: https://dev-id.socious.io
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}
  /auth/session:
    post:
      summary: confirm session
      description: create auth session
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                code:
                  type: string
                  example: 1234444
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}
  /auth/refresh:
    post:
      summary: refresh jwt
      description: refresh jwt
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                refresh_token:
                  type: string
                  example: jwt_refresh_token
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}
  /projects:
    get:
      summary: get projects
      security:
        - bearerAuth: []
      description: get projects
      tags:
        - Project
      responses:
        '200':
          description: Successful response
      parameters:
        - name: filter.identity
          in: query
          schema:
            type: string
          required: false
    post:
      summary: create projects
      security:
        - bearerAuth: []
      description: create projects
      tags:
        - Project
      parameters:
      - name: Current-Identity
        in: header
        schema:
          type: string
        example: ebd02a72-f530-4d18-9a72-d7aa9ace1271
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  title:
                    type: string
                    example: Title of the Service
                  description:
                    type: string
                    example: Description of the Service
                  status:
                    enum:
                      - DRAFT
                      - EXPIRE
                      - ACTIVE
                  city:
                    type: string
                  country:
                    type: string
                  social_cause:
                    type: string
                  cover_id:
                    type: string
                  wallet_address:
                    type: string
                  wallet_env:
                    type: string
                  website:
                    type: string
  /projects/:id:
    parameters:
      - name: id
        required: true
        in: path
        description: Project ID
        schema:
          type: string
    get:
      summary: get project
      security:
        - bearerAuth: []
      description: get project
      tags:
        - Project
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  title:
                    type: string
                    example: Title of the Service
                  description:
                    type: string
                    example: Description of the Service
                  status:
                    enum:
                      - DRAFT
                      - EXPIRE
                      - ACTIVE
                  city:
                    type: string
                  country:
                    type: string
                  social_cause:
                    type: string
                  cover_id:
                    type: string
                  wallet_address:
                    type: string
                  wallet_env:
                    type: string
                  website:
                    type: string
    patch:
      summary: update projects
      security:
        - bearerAuth: []
      description: create projects
      tags:
        - Project
      parameters:
      - name: Current-Identity
        in: header
        schema:
          type: string
        example: ebd02a72-f530-4d18-9a72-d7aa9ace1271
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  title:
                    type: string
                    example: Title of the Service
                  description:
                    type: string
                    example: Description of the Service
                  status:
                    enum:
                      - DRAFT
                      - EXPIRE
                      - ACTIVE
                  city:
                    type: string
                  country:
                    type: string
                  social_cause:
                    type: string
                  cover_id:
                    type: string
                  wallet_address:
                    type: string
                  wallet_env:
                    type: string
                  website:
                    type: string
    delete:
      summary: delete project
      security:
        - bearerAuth: []
      description: delete project
      tags:
        - Project
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
  /media:
    post:
      summary: upload media
      description: upload media
      security:
        - bearerAuth: []
      tags:
        - Media
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}
  /media/:id:
    parameters:
      - name: id
        required: true
        in: path
        description: Media ID
        schema:
          type: string
    get:
      summary: get media
      security:
        - bearerAuth: []
      description: get media
      tags:
        - Media
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}
  /users/profile:
    get:
      summary: get current user profile
      security:
        - bearerAuth: []
      description: get user profile
      tags:
        - Users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}
  /identities:
    get:
      summary: get current user identities
      security:
        - bearerAuth: []
      description: get current user identities
      tags:
        - Identities
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}

  /kybs:
    post:
        summary: new kyb
        security:
          - bearerAuth: []
        description:  new kyb for current organization
        tags:
          - KYB
        parameters:
          - name: Current-Identity
            in: header
            schema:
              type: string
            example: ebd02a72-f530-4d18-9a72-d7aa9ace1271
        responses:
          '200':
            description: Successful response
            content:
              application/json:
                schema:
                  properties:
                    documents:
                      type: array
                      items:
                        type: string
                      example: ["http://media_url_1", "http://media_url_2", "http://media_url_3"]
    get:
      summary: get kyb
      security:
        - bearerAuth: []
      description: get current organization kyb
      tags:
        - KYB
      parameters:
        - name: Current-Identity
          in: header
          schema:
            type: string
          example: ebd02a72-f530-4d18-9a72-d7aa9ace1271
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  user_id:
                    type: string
                  organization_id:
                    type: string
                  status:
                    type: string
                    enum:
                      - PENDING
                      - APPROVED
                      - REJECTED
                  documents:
                    type: array
                    items:
                      type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string