openapi: 3.0.0
info:
  title: Socious-API
  version: 2.2.6
servers:
  - url: http://localhost:4000
    description: Local server (for development purposes)
paths:
  /auth:
    post:
      summary: create auth
      security:
        - bearerAuth: []
      description: create auth session
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                redirect_url:
                  type: string
                  example: https://dev-id.socious.io
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}
  /auth/session:
    post:
      summary: confirm session
      security:
        - bearerAuth: []
      description: create auth session
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                code:
                  type: string
                  example: 1234444
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}